[environments]
  [environments.development]
    name = "pitchmatchapi"
    namespace = "default"
    wait = true
    watch = true
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile.develop"
    chart = "charts/pitchmatchapi"