version: '3.4'

services:
  pitch.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - pitchnetwork
    container_name: identity
networks:
  pitchnetwork:
    external: true