version: '3.4'

services:
  pitch.identity.api:
    image: ${DOCKER_REGISTRY-}pitchidentityapi
    build:
      context: .
      dockerfile: Pitch.Identity.Api/Dockerfile
    networks:
      - pitchnetwork
    container_name: identity
networks:
  pitchnetwork:
    external: true