version: '3'

services:
 identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=b81defd8-be86-4464-b1f2-056cc660fc4f
    build: .
    ports:
     - "8080:80"
    volumes:
    - "$APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets/"
    - "$HOME/.microsoft/usersecrets:/root/.microsoft/usersecrets/"
    networks:
      - mynetwork
    container_name: identity
networks:
  mynetwork:
    external: true