[environments]
  [environments.development]
    name = "identity"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = "../../k8s/helm/identity"
