apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui:v3.14.1
          ports:
            - containerPort: 8080
          env:
          - name: BASE_URL
            value: /swagger-ui
          - name: API_URLS
            value: >-
              [
              {url:'/match/swagger/v1/swagger.json',name:'Match API'},
              {url:'/user/swagger/v1/swagger.json',name:'User API'},
              {url:'/store/swagger/v1/swagger.json',name:'Store API'},
              {url:'/squad/swagger/v1/swagger.json',name:'Squad API'},
              {url:'/card/swagger/v1/swagger.json',name:'Card API'},
              ]


kind: Service
apiVersion: v1
metadata:
  name: swagger-ui
spec:
  selector:
    app: swagger-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080