version: '3.4'

services:
  pitch.gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      - pitchnetwork
    container_name: localhost.pitch-game.io
networks:
  pitchnetwork:
    external: true