apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        env:
          - name: "ConnectionStrings__ServiceBus"
            valueFrom:
              secretKeyRef:
                key:  "ServiceBus"
                name: "connection-strings"
          - name: "ConnectionStrings__MongoDb"
            valueFrom:
              secretKeyRef:
                key:  "MongoDb"
                name: "connection-strings"
          - name: "ConnectionStrings__RabbitMQHealthCheck"
            valueFrom:
              secretKeyRef:
                key:  "RabbitMQHealthCheck"
                name: "connection-strings"
        resources:
{{ toYaml .Values.resources | indent 12 }}
