# Default values for c#.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "match"

replicaCount: 1
image:
  repository: pitchgame/match.api
  pullPolicy: IfNotPresent
service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: false
